name       : haskell-fgl
version    : 5.7.0.2
release    : 4
source     :
    - https://hackage.haskell.org/package/fgl-5.7.0.2/fgl-5.7.0.2.tar.gz : 945a9acf5883c9f20a23d02d345227d1c617e8449db5c18f40c50b69246ff88f
license    : BSD-3-Clause
component  : programming.haskell
summary    : An inductive representation of manipulating graph data structures.
description: |
    An inductive representation of manipulating graph data structures.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
