name       : haskell-fgl
version    : 5.5.3.0
release    : 2
source     :
    - http://hackage.haskell.org/package/fgl-5.5.3.0/fgl-5.5.3.0.tar.gz : d70cd8e2694311fae0b44fe0d1b342c95706ceffd3be66767e9027dfa5597e39
license    : BSD-3-Clause
component  : programming.haskell
summary    : An inductive representation of manipulating graph data structures.
description: |
    An inductive representation of manipulating graph data structures.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
